#!/bin/sh
# 
# AntiShutdown Script to prevent shutdown or reboot of a server
# 
# chkconfig: 2345 99 00
# description: Prohibits the reboot or shutdown or a server
#
### BEGIN INIT INFO
# Provides: $AntiShutdown
### END INIT INFO

set -o nounset
set -o noclobber


CALLED="$0"
RUNLEVEL_MSG="$(who -r)"
RUNLEVEL="${RUNLEVEL_MSG#*run-level }"
REBOOTFILE=/root/.rebootallowed

MAIL_DST="adrien.mahieux@gmail.com"
MAIL_SUB="[YOUSHALLNOTSHUTDOWN] $(uname -n) entering runlevel $RUNLEVEL"
MAIL_TXT="This is script $0 on $(uname -n)

Currently connected users :
$(who)

Running processes :
$(ps auxf)


Have a nice day
"


checksys () {
	_myname="${CALLED##*/}"
	_myname="${_myname#S??}"
	
	_basepath="/var/lock/subsys"
	_reqfile="$_basepath/$_myname"
	[ -f "$_reqfile" ] || touch "$_reqfile"
	
	[ -f "$_reqfile" ]
}


verifyshutdown () {
	# YOU SHALL NOT STOP ME !
	if [ ! -e "$REBOOTFILE" ]; then
	
		_parentpid="$(ps -p $$ -o ppid=)"
		cat <<- EOT | wall
		##########################################################
		################ SHUTDOWN CANCELED #######################
		##########################################################
		     Unable to find file '$REBOOTFILE'
		##########################################################
		################ SHUTDOWN CANCELED #######################
		##########################################################
		EOT
		
		echo "$MAIL_TXT" | mail -s "$MAIL_SUB (cancelled)" "$MAIL_DST"
		
		echo "init 3" | at now + 1 minute
		kill -9 $_parentpid
	else
		rm $REBOOTFILE
		echo "$MAIL_TXT" | mail -s "$MAIL_SUB (allowed)" "$MAIL_DST"
		
	fi
	
}


case "${1:-}" in
	start)
		checksys
		;;
	stop)
		verifyshutdown
		;;

	*)
		echo "Usage: $0 <start|stop>"
		exit 1
		;;
esac
